# Generated by Django 4.2.7 on 2024-04-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_accepted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
    ]
